HbmartinRuleSet:
  AvoidFirstOnList:
    active: true
  AvoidVarsExceptWithDelegate:
    active: true
    allowedDelegates:
      - 'remember\w*'
  DontForceCast:
    active: true
  MutableTypeShouldBePrivate:
    active: true
